"use strict";var timer,$btn=$("#searchBtn"),goingText="&nbsp;<i class=\"fa fa-2x fa-star\"></i>&nbsp;Going!</a>",attendText="Attend&nbsp;<i class=\"fa fa-2x fa-star-o\"></i></a>",lastSearch="";// Populate page with search results (called from search function)
function displayBusinesses(a){var b=JSON.parse(a);// Clear previous search results and timer
// Display the results
// After all results are displayed, update attendance stats and UI
$("#results").empty(),clearTimeout(timer),b.forEach(function(a,b){// Convert and round distance (in meters) to miles
var c=(.000621371192*a.distance).toFixed(1),d=a.image_url?a.image_url:"/public/img/blank.png";// If necessary, replace blank business image with placeholder
// Display results with staggered animation
setTimeout(function(){$("#results").append("\n        <div class=\"col m6 l4 card-div animated fadeIn\">\n          <div class=\"card small black\">\n            <div class=\"card-image waves-effect waves-block waves-light\">\n              <img class=\"activator business-img\" src=\"".concat(d,"\" alt=\"").concat(a.name,"\">\n            </div>\n            <div class=\"card-content black\">\n              <span class=\"card-title activator white-text\">").concat(a.name,"<i class=\"material-icons right\">more_vert</i></span>\n              <p>").concat(c," mi.</p>\n              <p class=\"btm-right-text\"><a class=\"attend-link right hidden\" id=\"").concat(a.id,"\" href=\"javascript:;\" onclick=\"attend(this, true)\">").concat(attendText,"</a></p>\n            </div>\n            <div class=\"card-reveal black\">\n              <span class=\"card-title white-text\">").concat(a.name,"\n              <i class=\"material-icons right\">close</i></span>\n              <p>").concat(a.location.display_address.join("<br>"),"\n                  <br><a href=\"tel:").concat(a.phone,"\" target=\"_blank\">").concat(a.display_phone,"</a>\n              </p>\n              <p><a class=\"yelp\" href=\"").concat(a.url,"\" target=\"_blank\">View on <img class=\"yelp-logo\" src=\"/public/img/yelp.png\" alt=\"Yelp\"></a></p>\n              <p class=\"attendance\"><span id=\"").concat(a.id,"-attendance\">0</span>&nbsp;going</p>\n            </div>\n          </div>\n        </div>\n      "))},80*b)}),setTimeout(function(){checkAll(),$(".progress").addClass("hidden"),$btn.removeClass("disabled"),$btn.html("Search")},100*b.length)}// Search for results via GET request
function search(a){// First, ensure search field is populated and doesn't contain invalid characters
return!a.trim()||a.match(/[^a-zA-Z0-9.,\-\s]/)?Materialize.toast("Please enter a valid location",3e3,"error"):a.trim().toLowerCase()===lastSearch?Materialize.toast("Please enter a new location",3e3,"error"):void(// Update the UI and perform the search
// 7-second timer to prevent search hang-up
$(".card-div").addClass("fadeOut"),$(".progress").removeClass("hidden"),$btn.addClass("disabled"),$btn.html("<i class=\"fa fa-spinner fa-spin fa-fw\"></i>"),ajaxFunctions.ajaxRequest("GET","/api/list/".concat(a),displayBusinesses),lastSearch=a.trim().toLowerCase(),timer=setTimeout(function(){Materialize.toast("Search took too long. Please try again.",3e3,"error"),lastSearch="",$("#locationInput").val(""),$(".progress").addClass("hidden"),$btn.removeClass("disabled"),$btn.html("Search")},7e3));// Then, ensure user entered a new location (to prevent duplicate requests)
}// Check all search results for attendance stats
function checkAll(){var a=localStorage.getItem("rv-nightlife-id")||null;$(".attend-link").each(function(){var b=this;ajaxFunctions.ajaxRequest("GET","/api/attend/".concat($(this)[0].id,"/").concat(a),function(c){var d=JSON.parse(c);// If no data in DB, there are no stats to update
if(!d)return $(b).addClass("animated fadeInUp").removeClass("hidden");// Otherwise, update the link and attendance stats
var e=d.attendees.includes(a)?"attending":"no";updateAttending({location:d.location,total:d.attendees.length,action:e})})})}// Display user and guest attendance for each business
function updateAttending(a){// If data is from server, parse the string
var b="string"==typeof a?JSON.parse(a):a,c=$("#".concat(b.location));// Display the link
// Update attendance count
"attending"===b.action?(c.html(goingText),c.attr("onclick","attend(this)")):(c.html(attendText),c.attr("onclick","attend(this, true)")),c.addClass("animated fadeInUp").removeClass("hidden"),$("#".concat(b.location,"-attendance")).html(b.total)}// Handle attend link click
function attend(a,b){var c=localStorage.getItem("rv-nightlife-id");// First, check to see if user is logged in
if(!c)return $(".fb-buttons").addClass("shake"),setTimeout(function(){return $(".fb-buttons").removeClass("shake")},1e3),Materialize.toast("Please log in to attend events",2e3,"error");// Then, update the database (attend or unattend the location)
var d=b?"PUT":"DELETE";ajaxFunctions.ajaxRequest(d,"/api/attend/".concat(a.getAttribute("id"),"/").concat(c),updateAttending)}// Handle search button click
// Handle enter-key submission from search field
$btn.click(function(){return search($("#locationInput").val())}),$("#locationForm").on("submit",function(a){a.preventDefault(),search($("#locationInput").val())});